import Head from 'next/head'
import Navbar from '../components/Navbar';
import HeroSection from '../components/HeroSection';
import Supports from '../components/Supports';
import Clients from '../components/Clients';

const settigs = {
  infinite: true,
  speed: 500,
  slidesToShow: 4,
  slidesToScroll: 1
}

export default function Home() {
  return (
    <div>
      <Head>
        <title></title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="relative overflow-hidden">
        <Navbar/>
        <main>
          <HeroSection/>
          {/* More main page content here... */}
          <Supports/>
          <Clients/>
        </main>
      </div>
    </div>
  )
}
